theme: jekyll-theme-minimal
title: Welcome to SK's website!
image: https://github.com/MsKiden/eskay.github.io/blob/master/images/IMG_7845.HEIC
description: I will use this page to document my OpenDoTT journey and previous projects!
